apiVersion: v1
kind: Pod
metadata:
  name: test-env-cm
spec:
  containers:
    - name: env-test
      image: alpine
      command: ["/bin/sh", "-c", "env; sleep 3600"]
      imagePullPolicy: IfNotPresent
      env:
        - name: APP_NAME # 環境變數名稱
          valueFrom:
            configMapKeyRef:
              name: test-config # ConfigMap 名稱
              key: APP_NAME # ConfigMap 的 key
        - name: APP_VERSION
          valueFrom:
            configMapKeyRef:
              name: test-config
              key: APP_VERSION
  restartPolicy: Never